# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mohnish/github/KDE-Tasks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mohnish/github/KDE-Tasks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"kdetasks\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mohnish/github/KDE-Tasks/CMakeFiles /home/mohnish/github/KDE-Tasks//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mohnish/github/KDE-Tasks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named fetch-translations

# Build rule for target.
fetch-translations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fetch-translations
.PHONY : fetch-translations

# fast build rule for target.
fetch-translations/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fetch-translations.dir/build.make CMakeFiles/fetch-translations.dir/build
.PHONY : fetch-translations/fast

#=============================================================================
# Target rules for targets named generate_qmlls_build_ini_file

# Build rule for target.
generate_qmlls_build_ini_file: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_qmlls_build_ini_file
.PHONY : generate_qmlls_build_ini_file

# fast build rule for target.
generate_qmlls_build_ini_file/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_qmlls_build_ini_file.dir/build.make CMakeFiles/generate_qmlls_build_ini_file.dir/build
.PHONY : generate_qmlls_build_ini_file/fast

#=============================================================================
# Target rules for targets named all_aotstats

# Build rule for target.
all_aotstats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_aotstats
.PHONY : all_aotstats

# fast build rule for target.
all_aotstats/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_aotstats.dir/build.make CMakeFiles/all_aotstats.dir/build
.PHONY : all_aotstats/fast

#=============================================================================
# Target rules for targets named kdetasksplugin

# Build rule for target.
kdetasksplugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kdetasksplugin
.PHONY : kdetasksplugin

# fast build rule for target.
kdetasksplugin/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/kdetasksplugin.dir/build.make src/CMakeFiles/kdetasksplugin.dir/build
.PHONY : kdetasksplugin/fast

#=============================================================================
# Target rules for targets named qt_internal_plugins

# Build rule for target.
qt_internal_plugins: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qt_internal_plugins
.PHONY : qt_internal_plugins

# fast build rule for target.
qt_internal_plugins/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/qt_internal_plugins.dir/build.make src/CMakeFiles/qt_internal_plugins.dir/build
.PHONY : qt_internal_plugins/fast

#=============================================================================
# Target rules for targets named kdetasksplugin_qmltyperegistration

# Build rule for target.
kdetasksplugin_qmltyperegistration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kdetasksplugin_qmltyperegistration
.PHONY : kdetasksplugin_qmltyperegistration

# fast build rule for target.
kdetasksplugin_qmltyperegistration/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/kdetasksplugin_qmltyperegistration.dir/build.make src/CMakeFiles/kdetasksplugin_qmltyperegistration.dir/build
.PHONY : kdetasksplugin_qmltyperegistration/fast

#=============================================================================
# Target rules for targets named all_qmltyperegistrations

# Build rule for target.
all_qmltyperegistrations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmltyperegistrations
.PHONY : all_qmltyperegistrations

# fast build rule for target.
all_qmltyperegistrations/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/all_qmltyperegistrations.dir/build.make src/CMakeFiles/all_qmltyperegistrations.dir/build
.PHONY : all_qmltyperegistrations/fast

#=============================================================================
# Target rules for targets named kdetasksplugin_qmllint

# Build rule for target.
kdetasksplugin_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kdetasksplugin_qmllint
.PHONY : kdetasksplugin_qmllint

# fast build rule for target.
kdetasksplugin_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/kdetasksplugin_qmllint.dir/build.make src/CMakeFiles/kdetasksplugin_qmllint.dir/build
.PHONY : kdetasksplugin_qmllint/fast

#=============================================================================
# Target rules for targets named kdetasksplugin_qmllint_json

# Build rule for target.
kdetasksplugin_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kdetasksplugin_qmllint_json
.PHONY : kdetasksplugin_qmllint_json

# fast build rule for target.
kdetasksplugin_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/kdetasksplugin_qmllint_json.dir/build.make src/CMakeFiles/kdetasksplugin_qmllint_json.dir/build
.PHONY : kdetasksplugin_qmllint_json/fast

#=============================================================================
# Target rules for targets named kdetasksplugin_qmllint_module

# Build rule for target.
kdetasksplugin_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kdetasksplugin_qmllint_module
.PHONY : kdetasksplugin_qmllint_module

# fast build rule for target.
kdetasksplugin_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/kdetasksplugin_qmllint_module.dir/build.make src/CMakeFiles/kdetasksplugin_qmllint_module.dir/build
.PHONY : kdetasksplugin_qmllint_module/fast

#=============================================================================
# Target rules for targets named all_qmllint

# Build rule for target.
all_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint
.PHONY : all_qmllint

# fast build rule for target.
all_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/all_qmllint.dir/build.make src/CMakeFiles/all_qmllint.dir/build
.PHONY : all_qmllint/fast

#=============================================================================
# Target rules for targets named all_qmllint_json

# Build rule for target.
all_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint_json
.PHONY : all_qmllint_json

# fast build rule for target.
all_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/all_qmllint_json.dir/build.make src/CMakeFiles/all_qmllint_json.dir/build
.PHONY : all_qmllint_json/fast

#=============================================================================
# Target rules for targets named all_qmllint_module

# Build rule for target.
all_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint_module
.PHONY : all_qmllint_module

# fast build rule for target.
all_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/all_qmllint_module.dir/build.make src/CMakeFiles/all_qmllint_module.dir/build
.PHONY : all_qmllint_module/fast

#=============================================================================
# Target rules for targets named kdetasksplugin_copy_qml

# Build rule for target.
kdetasksplugin_copy_qml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kdetasksplugin_copy_qml
.PHONY : kdetasksplugin_copy_qml

# fast build rule for target.
kdetasksplugin_copy_qml/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/kdetasksplugin_copy_qml.dir/build.make src/CMakeFiles/kdetasksplugin_copy_qml.dir/build
.PHONY : kdetasksplugin_copy_qml/fast

#=============================================================================
# Target rules for targets named kdetasksplugin_copy_res

# Build rule for target.
kdetasksplugin_copy_res: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kdetasksplugin_copy_res
.PHONY : kdetasksplugin_copy_res

# fast build rule for target.
kdetasksplugin_copy_res/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/kdetasksplugin_copy_res.dir/build.make src/CMakeFiles/kdetasksplugin_copy_res.dir/build
.PHONY : kdetasksplugin_copy_res/fast

#=============================================================================
# Target rules for targets named kdetasksplugin_autogen_timestamp_deps

# Build rule for target.
kdetasksplugin_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kdetasksplugin_autogen_timestamp_deps
.PHONY : kdetasksplugin_autogen_timestamp_deps

# fast build rule for target.
kdetasksplugin_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/kdetasksplugin_autogen_timestamp_deps.dir/build.make src/CMakeFiles/kdetasksplugin_autogen_timestamp_deps.dir/build
.PHONY : kdetasksplugin_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named kdetasksplugin_autogen

# Build rule for target.
kdetasksplugin_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kdetasksplugin_autogen
.PHONY : kdetasksplugin_autogen

# fast build rule for target.
kdetasksplugin_autogen/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/kdetasksplugin_autogen.dir/build.make src/CMakeFiles/kdetasksplugin_autogen.dir/build
.PHONY : kdetasksplugin_autogen/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... all_aotstats"
	@echo "... all_qmllint"
	@echo "... all_qmllint_json"
	@echo "... all_qmllint_module"
	@echo "... all_qmltyperegistrations"
	@echo "... fetch-translations"
	@echo "... generate_qmlls_build_ini_file"
	@echo "... kdetasksplugin_autogen"
	@echo "... kdetasksplugin_autogen_timestamp_deps"
	@echo "... kdetasksplugin_copy_qml"
	@echo "... kdetasksplugin_copy_res"
	@echo "... kdetasksplugin_qmllint"
	@echo "... kdetasksplugin_qmllint_json"
	@echo "... kdetasksplugin_qmllint_module"
	@echo "... kdetasksplugin_qmltyperegistration"
	@echo "... qt_internal_plugins"
	@echo "... uninstall"
	@echo "... kdetasksplugin"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

